- alias: "Turn hallway lamp off"
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    condition: state
    entity_id: light.hallway_rooms_2
    state: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 45
  action:
    service: light.turn_off
    data:
      entity_id: light.hallway_rooms_2
      transition: 15

- alias: "Me is home"
  trigger:
    platform: state
    entity_id: device_tracker.<tracker_id>
    from: 'not_home'
    to: 'home'
  action:
    service: notify.telegram_bot
    data:
      message: 'Me is now home'
